github.com:
    users:
        riaanjlagrange:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: riaanjlagrange
